AJAX_Demo/Models/AjaxViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AJAX_Demo.Models
{
    public class AjaxViewModel
    {
        public string txtFirstNo { get; set; }

        public string txtSecondNo { get; set; }
    }
}

AJAX_Demo/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AJAX_Demo.Models;
using System.Web.Mvc;

namespace AJAX_Demo.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public string Index(string txtFirstNo, string txtSecondNo)
        //{
        //    var result = int.Parse(txtFirstNo) + int.Parse(txtSecondNo);
        //    return result.ToString();
        //}

        [HttpPost]
        public string Index(AjaxViewModel m)
        {
            var result = int.Parse(m.txtFirstNo) + int.Parse(m.txtSecondNo);
            return result.ToString();
        }
    }
}

AJAX_Demo/Controllers/JQAjaxController.cs
using AJAX_Demo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AJAX_Demo.Controllers
{
    public class JQAjaxController : Controller
    {
        // GET: JQAjax
        public ActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public string Index(string txtFirstNo, string txtSecondNo)
        //{
        //    var result = int.Parse(txtFirstNo) + int.Parse(txtSecondNo);
        //    return result.ToString();
        //}

        [HttpPost]
        public string Index(AjaxViewModel m)
        {
            var result = int.Parse(m.txtFirstNo) + int.Parse(m.txtSecondNo);
            return result.ToString();
        }
    }
}

AJAX_Demo/Views/Ajax/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" ></script>
</head>
<body>
    <div>
        @using (Ajax.BeginForm(
            "Index",
            "Ajax",
            null,
            new AjaxOptions {
                UpdateTargetId = "lblResult",
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "POST"
            },
            new { id = "SampleForm" }))
        {
            <span>Enter first no:</span>@Html.TextBox("txtFirstNo")<br />
            <span>Enter second no:</span>@Html.TextBox("txtSecondNo")<br />
            <span id="lblResult"></span>
            <button type="submit">Show</button>
        }  
    </div>
</body>
</html>

AJAX_Demo/Views/JQAjax/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body>
    <div> 
        <span>Enter first no:</span>@Html.TextBox("txtFirstNo")<br />
        <span>Enter second no:</span>@Html.TextBox("txtSecondNo")<br />
        <span id="lblResult"></span>
        <button type="button" onclick="doSum();">Show</button>
    </div>

    <script>

        function doSum() {
            var v1 = $("#txtFirstNo").val();
            var v2 = $("#txtSecondNo").val();

            @*$.ajax({
                url: '@Url.Action("Index", "JQAjax")',
                method: "POST",
                cache: false,
                data: {txtFirstNo: v1, txtSecondNo: v2}
            }).done(function (data) {
                $("#lblResult").text(data);
            });*@

            $.post('@Url.Action("Index", "JQAjax")',
                { txtFirstNo: v1, txtSecondNo: v2 })
                .done(function (data) {
                $("lblResult").text(data);
            });
        }

    </script>
</body>
</html>